### ISSUE TITLE
index-arm64-darwin

### ISSUE THREAD

**Issue by MarkusLohmayer** [Mic92/nix-index-database#18]
Is there a reason why index-arm64-darwin is not available?

**Comment by Mic92** [comment]
We do not CI support for arm64 so we cannot run `nix-index` on it.

**Comment by MarkusLohmayer** [comment]
Surely an ignorant question, but why is it required to have a CPU with a given architecture to figure out which Nix packages contain specific (executable) files? I mean, it should not be required to execute the files, which would of course demand to have an arm64 CPU.

**Comment by Mic92** [comment]
Potentially it is not, maybe you can try to run this for aarch64-darwin system on a our x86_64-linux CI github action. I have not tried.

**Comment by Mic92** [comment]
I know when aarch64-linux was added, also qemu binfmt was set up.

**Comment by Mic92** [comment]
fixed: https://github.com/Mic92/nix-index-database/releases/tag/2022-12-25
