### ISSUE TITLE
How to use nix-index on macOS?

### ISSUE THREAD

**Issue by MarkusLohmayer** [Mic92/nix-index-database#29]
First of all, thank you very much for working on #18

I am now trying to get nix-index running on my macOS system.

I have added the home-manager module as described in the README: 
https://github.com/MarkusLohmayer/nix-config/blob/main/flake.nix#L86

However, I had to remove
`programs.nix-index.enable = true;` from my home-manager config, see
https://github.com/MarkusLohmayer/nix-config/blob/main/flake.nix#L86
since I got the following error
```
error: builder for '/nix/store/2mngnj7w1fp5r9lwaibpyh1l6knsl9c5-home-manager-path.drv' failed with exit code 25;
       last 1 log lines:
       > error: collision between `/nix/store/nb4rk64wwcw4yhf8fmwq5q23pskhwx2f-nix-index-unstable-2022-03-07/bin/nix-locate' and `/nix/store/z2vk3mq7a5cmrsqkhcgx5rqv89g2blll-nix-index/bin/nix-locate'
```

Any hints for helping me to correctly setup nix-index on macOS are appreciated.
Thanks again! 😄

**Comment by Mic92** [comment]
This is now possible with https://github.com/Mic92/nix-index-database/pull/28/commits/75e347f5b4ac8029dafdcdb38b589d42f5ba1553

**Comment by MarkusLohmayer** [comment]
@Mic92 I did what the README says, but I get the following error when I apply the nix config: ```error: collision between `/nix/store/nb4rk64wwcw4yhf8fmwq5q23pskhwx2f-nix-index-unstable-2022-03-07/bin/nix-locate' and `/nix/store/z2vk3mq7a5cmrsqkhcgx5rqv89g2blll-nix-index/bin/nix-locate'``` Any ideas?

**Comment by Mic92** [comment]
When you update the flake so that it includes https://github.com/Mic92/nix-index-database/pull/28
Than you there is no collision with `programs.nix-index.enable = true;` anymore.

**Comment by Mic92** [comment]
see this: https://github.com/Mic92/nix-index-database/pull/28/files#diff-ff0b531db429db2a3473c0d8242f649b4481de76343a98d026eeb864588338d9R7

**Comment by MarkusLohmayer** [comment]
Oh yes of course, thanks!!! The HM did not update properly because some packages `ncdu` seems to be broken atm, so I commented it out and now the update and hence the index works.

Would you perhaps also know why [comma](https://github.com/nix-community/comma) does still not work?
```
Warning: Nix-index database does not exist, try updating with `--update`.
nix-locate failed with: error: reading from the database at '/Users/markus/.cache/nix-index/files' failed.
This may be caused by a corrupt or missing database, try (re)running `nix-index` to generate the database. 
If the error persists please file a bug report at https://github.com/bennofs/nix-index.
caused by: No such file or directory (os error 2)
```

**Comment by Mic92** [comment]
You will need to do something like `comma.override { nix-index = nix-index-from-this-flake; }` for it to work.
