### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by szaffarano** [Mic92/nix-index-database#48]
Not sure if it's something related to [comma](https://github.com/nix-community/comma), but after #47 I had to remove the `comma` package from my `home-manager` config since I got

```
> error: collision between `/nix/store/l2x9kyb234qzrjyih36zfv2mk87m2b83-comma-with-db-1.6.0/bin/,' and `/nix/store/ch4s39pafpnm24fm9gpjqqpp494v8qm0-comma-1.6.0/bin/,'
```

Now although everything is fine, when I try to run any `comma` command I get

```
❯ , ls
error: creating directory '/nix/store/l2x9kyb234qzrjyih36zfv2mk87m2b83-comma-with-db-1.6.0/share/cache/nix': Permission denied
```

but using the "real" `comma` binary, it works as expected, i.e.:

```
/nix/store/ch4s39pafpnm24fm9gpjqqpp494v8qm0-comma-1.6.0/bin/comma ls
```

It looks like the overridden `XDG_CACHE_HOME` env variable in the wrapper is causing problems.  Am I missing something?

Thanks!

**Comment by Mic92** [comment]
Ah. is the issue maybe not comma but nix, that tries to create this?

**Comment by szaffarano** [comment]
Forgot to mention (sorry), I'm using Arch among with `home-manager`

```
❯ cat $(realpath $(which ,))
#! /nix/store/j80wcbm6bb1nsqsgmniq43rg980p27q9-bash-5.2-p15/bin/bash -e
export XDG_CACHE_HOME='/nix/store/l2x9kyb234qzrjyih36zfv2mk87m2b83-comma-with-db-1.6.0/share/cache'
exec "/nix/store/ch4s39pafpnm24fm9gpjqqpp494v8qm0-comma-1.6.0/bin/,"  "$@" 

❯ tree /nix/store/l2x9kyb234qzrjyih36zfv2mk87m2b83-comma-with-db-1.6.0/share/cache
/nix/store/l2x9kyb234qzrjyih36zfv2mk87m2b83-comma-with-db-1.6.0/share/cache
└── nix-index
    └── files -> /nix/store/p1fv6pmynmd276lrf8dfh8f9rlnwm0zs-index-x86_64-linux
```

Thanks for the prompt reply!

**Comment by Mic92** [comment]
Yes. The issue is nix and not comma here. It also tries to use the environment variable set this wrapper.
