### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by Artturin** [Mic92/nix-index-database#56]
https://github.com/Mic92/nix-index-database/actions

**Comment by R-VdP** [comment]
I wonder if the jobs are simply going OOM. When I launch the x86-64 one manually on a server with 62GB of memory, it uses up all the memory and gets killed...
The i686 one completes without error locally.

**Comment by Mic92** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/232259

**Comment by Mic92** [comment]
I disabled i686-linux for now: https://github.com/Mic92/nix-index-database/commit/e171cb06e7f77cc506e0712dd0a67530de1c80e3
also we have https://github.com/NixOS/nixpkgs/pull/232259
